[tool.poetry]
name = "akiha-assets"
version = "0.1.0"
description = ""
authors = ["Skimige <me@xyx.moe>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
