# This is a basic workflow to help you get started with Actions

name: Fetch Data

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get latest data and update
        env:
          WAHLAP_SHOP_API_URL: ${{ secrets.WAHLAP_SHOP_API_URL }}
          ALIAS_SHEET_TSV_URL: ${{ secrets.ALIAS_SHEET_TSV_URL }}
        run: |
          bash fetch.sh
