name: Fetch Data

on:
  schedule:
    - cron: "15,45 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest data and update
        env:
          WAHLAP_CHUNITHM_SHOP_DATA_URL: ${{ secrets.WAHLAP_CHUNITHM_SHOP_DATA_URL }}
          WAHLAP_MAIMAI_SHOP_DATA_URL: ${{ secrets.WAHLAP_MAIMAI_SHOP_DATA_URL }}
          ALIAS_SHEET_TSV_URL: ${{ secrets.ALIAS_SHEET_TSV_URL }}
          MUSIC_DATA_URL: ${{ secrets.MUSIC_DATA_URL }}
          CHART_STATS_DATA_URL: ${{ secrets.CHART_STATS_DATA_URL }}
        run: |
          bash fetch.sh
